name: kanivis
description: Knowles' Audible Navigation for Visually Impaired Sailors

version: 1.0.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_tts: ^3.2.4
  intl: ^0.18.1
  shared_preferences: null
  audioplayers: ^5.2.1
  nmea:
    git:
      url: https://github.com/jamesdalby/nmea.git
      ref: master
  ais:
    git:
      url: https://github.com/jamesdalby/ais.git
      ref: master

  cupertino_icons: ^1.0.4
  collection: ^1.17.0
  wave_generator:
    git:
      url: https://github.com/jamesdalby/wave-generator.git
      ref: master
      
  geolocator: ^10.1.0
  flutter_compass: ^0.8.0
  permission_handler: ^11.1.0
  
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "svg/k1024.png"

flutter:
  uses-material-design: true
  generate: true 
  assets:
    - assets/beeps/
flutter_intl:
  enabled: true
